newman_labs:
  target: runtime
  outputs:
    runtime:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | int }}"
      user: "{{ env_var('PGUSER') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      sslmode: "{{ env_var('PGSSLMODE', 'prefer') }}"
      schema: analytics
      threads: 4
